package jstore;
// Generated 24/11/2010 08:39:34 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Contacto generated by hbm2java
 */
public class Contacto  implements java.io.Serializable {


     private Integer codigoContacto;
     private Proveedor proveedor;
     private String nombre;
     private String apellido;
     private String telefono;
     private String email;
     private Date fecCreacion;
     private Set contactoEstados = new HashSet(0);

    public Contacto() {
    }

    public Contacto(Proveedor proveedor, String nombre, String apellido, String telefono, String email, Date fecCreacion, Set contactoEstados) {
       this.proveedor = proveedor;
       this.nombre = nombre;
       this.apellido = apellido;
       this.telefono = telefono;
       this.email = email;
       this.fecCreacion = fecCreacion;
       this.contactoEstados = contactoEstados;
    }
   
    public Integer getCodigoContacto() {
        return this.codigoContacto;
    }
    
    public void setCodigoContacto(Integer codigoContacto) {
        this.codigoContacto = codigoContacto;
    }
    public Proveedor getProveedor() {
        return this.proveedor;
    }
    
    public void setProveedor(Proveedor proveedor) {
        this.proveedor = proveedor;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Date getFecCreacion() {
        return this.fecCreacion;
    }
    
    public void setFecCreacion(Date fecCreacion) {
        this.fecCreacion = fecCreacion;
    }
    public Set getContactoEstados() {
        return this.contactoEstados;
    }
    
    public void setContactoEstados(Set contactoEstados) {
        this.contactoEstados = contactoEstados;
    }




}


