package jstore;
// Generated 24/11/2010 08:39:34 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Movimiento generated by hbm2java
 */
public class Movimiento  implements java.io.Serializable {


     private Integer codigoMovimiento;
     private ProductoDetalle productoDetalle;
     private String tipo;
     private String destino;
     private Date fecActual;

    public Movimiento() {
    }

    public Movimiento(ProductoDetalle productoDetalle, String tipo, String destino, Date fecActual) {
       this.productoDetalle = productoDetalle;
       this.tipo = tipo;
       this.destino = destino;
       this.fecActual = fecActual;
    }
   
    public Integer getCodigoMovimiento() {
        return this.codigoMovimiento;
    }
    
    public void setCodigoMovimiento(Integer codigoMovimiento) {
        this.codigoMovimiento = codigoMovimiento;
    }
    public ProductoDetalle getProductoDetalle() {
        return this.productoDetalle;
    }
    
    public void setProductoDetalle(ProductoDetalle productoDetalle) {
        this.productoDetalle = productoDetalle;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    public String getDestino() {
        return this.destino;
    }
    
    public void setDestino(String destino) {
        this.destino = destino;
    }
    public Date getFecActual() {
        return this.fecActual;
    }
    
    public void setFecActual(Date fecActual) {
        this.fecActual = fecActual;
    }




}


