package jstore;
// Generated 24/11/2010 08:39:34 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * ProductoDetalle generated by hbm2java
 */
public class ProductoDetalle  implements java.io.Serializable {


     private Integer codigoProductoDell;
     private Tienda tienda;
     private Producto producto;
     private Proveedor proveedor;
     private Categoria categoria;
     private Integer cantidad;
     private Double costo;
     private Double precio;
     private Date fecCreacion;
     private String estado;
     private Set movimientos = new HashSet(0);

    public ProductoDetalle() {
    }

    public ProductoDetalle(Tienda tienda, Producto producto, Proveedor proveedor, Categoria categoria, Integer cantidad, Double costo, Double precio, Date fecCreacion, String estado, Set movimientos) {
       this.tienda = tienda;
       this.producto = producto;
       this.proveedor = proveedor;
       this.categoria = categoria;
       this.cantidad = cantidad;
       this.costo = costo;
       this.precio = precio;
       this.fecCreacion = fecCreacion;
       this.estado = estado;
       this.movimientos = movimientos;
    }
   
    public Integer getCodigoProductoDell() {
        return this.codigoProductoDell;
    }
    
    public void setCodigoProductoDell(Integer codigoProductoDell) {
        this.codigoProductoDell = codigoProductoDell;
    }
    public Tienda getTienda() {
        return this.tienda;
    }
    
    public void setTienda(Tienda tienda) {
        this.tienda = tienda;
    }
    public Producto getProducto() {
        return this.producto;
    }
    
    public void setProducto(Producto producto) {
        this.producto = producto;
    }
    public Proveedor getProveedor() {
        return this.proveedor;
    }
    
    public void setProveedor(Proveedor proveedor) {
        this.proveedor = proveedor;
    }
    public Categoria getCategoria() {
        return this.categoria;
    }
    
    public void setCategoria(Categoria categoria) {
        this.categoria = categoria;
    }
    public Integer getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(Integer cantidad) {
        this.cantidad = cantidad;
    }
    public Double getCosto() {
        return this.costo;
    }
    
    public void setCosto(Double costo) {
        this.costo = costo;
    }
    public Double getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(Double precio) {
        this.precio = precio;
    }
    public Date getFecCreacion() {
        return this.fecCreacion;
    }
    
    public void setFecCreacion(Date fecCreacion) {
        this.fecCreacion = fecCreacion;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public Set getMovimientos() {
        return this.movimientos;
    }
    
    public void setMovimientos(Set movimientos) {
        this.movimientos = movimientos;
    }




}


