package jstore;
// Generated 24/11/2010 08:39:34 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Producto generated by hbm2java
 */
public class Producto  implements java.io.Serializable {


     private int codigoProducto;
     private String presentacion;
     private Set productoDetalles = new HashSet(0);

    public Producto() {
    }

	
    public Producto(int codigoProducto) {
        this.codigoProducto = codigoProducto;
    }
    public Producto(int codigoProducto, String presentacion, Set productoDetalles) {
       this.codigoProducto = codigoProducto;
       this.presentacion = presentacion;
       this.productoDetalles = productoDetalles;
    }
   
    public int getCodigoProducto() {
        return this.codigoProducto;
    }
    
    public void setCodigoProducto(int codigoProducto) {
        this.codigoProducto = codigoProducto;
    }
    public String getPresentacion() {
        return this.presentacion;
    }
    
    public void setPresentacion(String presentacion) {
        this.presentacion = presentacion;
    }
    public Set getProductoDetalles() {
        return this.productoDetalles;
    }
    
    public void setProductoDetalles(Set productoDetalles) {
        this.productoDetalles = productoDetalles;
    }




}


