package jstore;
// Generated 24/11/2010 08:39:34 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * ProveedorEstado generated by hbm2java
 */
public class ProveedorEstado  implements java.io.Serializable {


     private Integer codigoProveedorEstado;
     private Proveedor proveedor;
     private Date fecIngreso;
     private Date fecSalida;
     private String estado;

    public ProveedorEstado() {
    }

    public ProveedorEstado(Proveedor proveedor, Date fecIngreso, Date fecSalida, String estado) {
       this.proveedor = proveedor;
       this.fecIngreso = fecIngreso;
       this.fecSalida = fecSalida;
       this.estado = estado;
    }
   
    public Integer getCodigoProveedorEstado() {
        return this.codigoProveedorEstado;
    }
    
    public void setCodigoProveedorEstado(Integer codigoProveedorEstado) {
        this.codigoProveedorEstado = codigoProveedorEstado;
    }
    public Proveedor getProveedor() {
        return this.proveedor;
    }
    
    public void setProveedor(Proveedor proveedor) {
        this.proveedor = proveedor;
    }
    public Date getFecIngreso() {
        return this.fecIngreso;
    }
    
    public void setFecIngreso(Date fecIngreso) {
        this.fecIngreso = fecIngreso;
    }
    public Date getFecSalida() {
        return this.fecSalida;
    }
    
    public void setFecSalida(Date fecSalida) {
        this.fecSalida = fecSalida;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }




}


