package jstore;
// Generated 24/11/2010 08:39:34 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Tienda generated by hbm2java
 */
public class Tienda  implements java.io.Serializable {


     private Integer codigoTienda;
     private Usuario usuario;
     private String duenio;
     private String ubicacion;
     private Set productoDetalles = new HashSet(0);

    public Tienda() {
    }

    public Tienda(Usuario usuario, String duenio, String ubicacion, Set productoDetalles) {
       this.usuario = usuario;
       this.duenio = duenio;
       this.ubicacion = ubicacion;
       this.productoDetalles = productoDetalles;
    }
   
    public Integer getCodigoTienda() {
        return this.codigoTienda;
    }
    
    public void setCodigoTienda(Integer codigoTienda) {
        this.codigoTienda = codigoTienda;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public String getDuenio() {
        return this.duenio;
    }
    
    public void setDuenio(String duenio) {
        this.duenio = duenio;
    }
    public String getUbicacion() {
        return this.ubicacion;
    }
    
    public void setUbicacion(String ubicacion) {
        this.ubicacion = ubicacion;
    }
    public Set getProductoDetalles() {
        return this.productoDetalles;
    }
    
    public void setProductoDetalles(Set productoDetalles) {
        this.productoDetalles = productoDetalles;
    }




}


