/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Login.java
 *
 * Created on 16/09/2010, 07:58:30 PM
 */
package almacenventas.view;

import modelo.Controlador;
import prueba.Usuarios;

/**
 *
 * @author willy
 */
public class Login extends javax.swing.JFrame {

    /** Creates new form Login */
    public Login() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanelIngreso = new javax.swing.JPanel();
        jPanelUsuarioPassword = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        jPanelBotones = new javax.swing.JPanel();
        btnIngresar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocationByPlatform(true);
        setResizable(false);

        jPanelIngreso.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(""), "Ingreso de Usuario"));

        jPanelUsuarioPassword.setBorder(null);
        jPanelUsuarioPassword.setLayout(new java.awt.GridLayout(2, 2));

        jLabel1.setText("Usuario");
        jPanelUsuarioPassword.add(jLabel1);
        jPanelUsuarioPassword.add(txtUsuario);

        jLabel2.setText("Password");
        jPanelUsuarioPassword.add(jLabel2);
        jPanelUsuarioPassword.add(txtPassword);

        jPanelBotones.setBorder(null);
        jPanelBotones.setEnabled(false);
        jPanelBotones.setLayout(new java.awt.GridLayout(1, 2));

        btnIngresar.setText("Ingresar");
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });
        jPanelBotones.add(btnIngresar);

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        jPanelBotones.add(btnSalir);

        javax.swing.GroupLayout jPanelIngresoLayout = new javax.swing.GroupLayout(jPanelIngreso);
        jPanelIngreso.setLayout(jPanelIngresoLayout);
        jPanelIngresoLayout.setHorizontalGroup(
            jPanelIngresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelIngresoLayout.createSequentialGroup()
                .addGroup(jPanelIngresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelIngresoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanelBotones, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelIngresoLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jPanelUsuarioPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanelIngresoLayout.setVerticalGroup(
            jPanelIngresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelIngresoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelUsuarioPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanelBotones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelIngreso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        java.awt.Dimension dialogSize = getSize();
        setLocation((screenSize.width-dialogSize.width)/2,(screenSize.height-dialogSize.height)/2);
    }// </editor-fold>                        

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
//        String u = txtUsuario.getText();
//        String pass = new String(txtPassword.getPassword());
//        Principal prin = new Principal();
//        ErrorUsuarioPassword errorup = new ErrorUsuarioPassword(prin, rootPaneCheckingEnabled);
//
//        if(u.equals("usuario") && pass.equals("usuario")){
//            prin.setVisible(true);
//            this.dispose();
//        }else{
//            errorup.setVisible(true);
//        }
        try {
            String user = txtUsuario.getText();
            String pass = new String(txtPassword.getPassword());
            Controlador c = new Controlador();
            c.validar(user, pass);            
            if (c.equals("x")) {
                System.out.println("EERROROR");
            } else {
                Principal prin = new Principal();
                prin.setVisible(true);
                this.dispose();
            }

        } catch (Exception e) {
            System.out.println(e);
        }


    }                                           

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        dispose();
    }                                        
    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify                     
    javax.swing.JButton btnIngresar;
    javax.swing.JButton btnSalir;
    javax.swing.JLabel jLabel1;
    javax.swing.JLabel jLabel2;
    javax.swing.JPanel jPanelBotones;
    javax.swing.JPanel jPanelIngreso;
    javax.swing.JPanel jPanelUsuarioPassword;
    javax.swing.JPasswordField txtPassword;
    javax.swing.JTextField txtUsuario;
    // End of variables declaration                   
}
