/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MyPanel.java
 *
 * Created on 17/11/2010, 09:06:25 AM
 */

package javaapplication1;

/**
 *
 * @author willly
 */
public class MyPanel extends java.awt.Panel {

    /** Creates new form MyPanel */
    public MyPanel() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new java.awt.BorderLayout());
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
