package persistencia;
// Generated 07/04/2010 08:17:43 PM by Hibernate Tools 3.2.1.GA



/**
 * Aula generated by hbm2java
 */
public class Aula  implements java.io.Serializable {


     private String codAula;
     private Integer capMax;
     private String tipoAula;

    public Aula() {
    }

	
    public Aula(String codAula) {
        this.codAula = codAula;
    }
    public Aula(String codAula, Integer capMax, String tipoAula) {
       this.codAula = codAula;
       this.capMax = capMax;
       this.tipoAula = tipoAula;
    }
   
    public String getCodAula() {
        return this.codAula;
    }
    
    public void setCodAula(String codAula) {
        this.codAula = codAula;
    }
    public Integer getCapMax() {
        return this.capMax;
    }
    
    public void setCapMax(Integer capMax) {
        this.capMax = capMax;
    }
    public String getTipoAula() {
        return this.tipoAula;
    }
    
    public void setTipoAula(String tipoAula) {
        this.tipoAula = tipoAula;
    }




}


