package persistencia;
// Generated 07/04/2010 08:17:43 PM by Hibernate Tools 3.2.1.GA



/**
 * Examen generated by hbm2java
 */
public class Examen  implements java.io.Serializable {


     private ExamenId id;
     private String enunciado;
     private Integer puntaje;
     private String tipo;

    public Examen() {
    }

	
    public Examen(ExamenId id) {
        this.id = id;
    }
    public Examen(ExamenId id, String enunciado, Integer puntaje, String tipo) {
       this.id = id;
       this.enunciado = enunciado;
       this.puntaje = puntaje;
       this.tipo = tipo;
    }
   
    public ExamenId getId() {
        return this.id;
    }
    
    public void setId(ExamenId id) {
        this.id = id;
    }
    public String getEnunciado() {
        return this.enunciado;
    }
    
    public void setEnunciado(String enunciado) {
        this.enunciado = enunciado;
    }
    public Integer getPuntaje() {
        return this.puntaje;
    }
    
    public void setPuntaje(Integer puntaje) {
        this.puntaje = puntaje;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }




}


