package persistencia;
// Generated 07/04/2010 08:17:43 PM by Hibernate Tools 3.2.1.GA



/**
 * ProgramarId generated by hbm2java
 */
public class ProgramarId  implements java.io.Serializable {


     private String semestre;
     private String curso;
     private int grupo;

    public ProgramarId() {
    }

    public ProgramarId(String semestre, String curso, int grupo) {
       this.semestre = semestre;
       this.curso = curso;
       this.grupo = grupo;
    }
   
    public String getSemestre() {
        return this.semestre;
    }
    
    public void setSemestre(String semestre) {
        this.semestre = semestre;
    }
    public String getCurso() {
        return this.curso;
    }
    
    public void setCurso(String curso) {
        this.curso = curso;
    }
    public int getGrupo() {
        return this.grupo;
    }
    
    public void setGrupo(int grupo) {
        this.grupo = grupo;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ProgramarId) ) return false;
		 ProgramarId castOther = ( ProgramarId ) other; 
         
		 return ( (this.getSemestre()==castOther.getSemestre()) || ( this.getSemestre()!=null && castOther.getSemestre()!=null && this.getSemestre().equals(castOther.getSemestre()) ) )
 && ( (this.getCurso()==castOther.getCurso()) || ( this.getCurso()!=null && castOther.getCurso()!=null && this.getCurso().equals(castOther.getCurso()) ) )
 && (this.getGrupo()==castOther.getGrupo());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getSemestre() == null ? 0 : this.getSemestre().hashCode() );
         result = 37 * result + ( getCurso() == null ? 0 : this.getCurso().hashCode() );
         result = 37 * result + this.getGrupo();
         return result;
   }   


}


