package joyeria;
// Generated 10-may-2010 15:42:23 by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;

/**
 * DetalleIngreso generated by hbm2java
 */
public class DetalleIngreso  implements java.io.Serializable {


     private int idDetalle;
     private Producto producto;
     private int cantidad;
     private BigDecimal precioUnit;

    public DetalleIngreso() {
    }

    public DetalleIngreso(int idDetalle, Producto producto, int cantidad, BigDecimal precioUnit) {
       this.idDetalle = idDetalle;
       this.producto = producto;
       this.cantidad = cantidad;
       this.precioUnit = precioUnit;
    }
   
    public int getIdDetalle() {
        return this.idDetalle;
    }
    
    public void setIdDetalle(int idDetalle) {
        this.idDetalle = idDetalle;
    }
    public Producto getProducto() {
        return this.producto;
    }
    
    public void setProducto(Producto producto) {
        this.producto = producto;
    }
    public int getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(int cantidad) {
        this.cantidad = cantidad;
    }
    public BigDecimal getPrecioUnit() {
        return this.precioUnit;
    }
    
    public void setPrecioUnit(BigDecimal precioUnit) {
        this.precioUnit = precioUnit;
    }




}


