package joyeria;
// Generated 10-may-2010 15:42:23 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Ingreso generated by hbm2java
 */
public class Ingreso  implements java.io.Serializable {


     private int idIngreso;
     private Proveedor proveedor;
     private String tipoIngreso;
     private String tipoDoc;
     private String serieDocIngreso;
     private String numeroDoc;
     private Date fechaIngreso;

    public Ingreso() {
    }

    public Ingreso(int idIngreso, Proveedor proveedor, String tipoIngreso, String tipoDoc, String serieDocIngreso, String numeroDoc, Date fechaIngreso) {
       this.idIngreso = idIngreso;
       this.proveedor = proveedor;
       this.tipoIngreso = tipoIngreso;
       this.tipoDoc = tipoDoc;
       this.serieDocIngreso = serieDocIngreso;
       this.numeroDoc = numeroDoc;
       this.fechaIngreso = fechaIngreso;
    }
   
    public int getIdIngreso() {
        return this.idIngreso;
    }
    
    public void setIdIngreso(int idIngreso) {
        this.idIngreso = idIngreso;
    }
    public Proveedor getProveedor() {
        return this.proveedor;
    }
    
    public void setProveedor(Proveedor proveedor) {
        this.proveedor = proveedor;
    }
    public String getTipoIngreso() {
        return this.tipoIngreso;
    }
    
    public void setTipoIngreso(String tipoIngreso) {
        this.tipoIngreso = tipoIngreso;
    }
    public String getTipoDoc() {
        return this.tipoDoc;
    }
    
    public void setTipoDoc(String tipoDoc) {
        this.tipoDoc = tipoDoc;
    }
    public String getSerieDocIngreso() {
        return this.serieDocIngreso;
    }
    
    public void setSerieDocIngreso(String serieDocIngreso) {
        this.serieDocIngreso = serieDocIngreso;
    }
    public String getNumeroDoc() {
        return this.numeroDoc;
    }
    
    public void setNumeroDoc(String numeroDoc) {
        this.numeroDoc = numeroDoc;
    }
    public Date getFechaIngreso() {
        return this.fechaIngreso;
    }
    
    public void setFechaIngreso(Date fechaIngreso) {
        this.fechaIngreso = fechaIngreso;
    }




}


