package joyeria;
// Generated 10-may-2010 15:42:23 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * TipoDocumentos generated by hbm2java
 */
public class TipoDocumentos  implements java.io.Serializable {


     private int idTipoDoc;
     private String descripcion;
     private Set vendedors = new HashSet(0);

    public TipoDocumentos() {
    }

	
    public TipoDocumentos(int idTipoDoc, String descripcion) {
        this.idTipoDoc = idTipoDoc;
        this.descripcion = descripcion;
    }
    public TipoDocumentos(int idTipoDoc, String descripcion, Set vendedors) {
       this.idTipoDoc = idTipoDoc;
       this.descripcion = descripcion;
       this.vendedors = vendedors;
    }
   
    public int getIdTipoDoc() {
        return this.idTipoDoc;
    }
    
    public void setIdTipoDoc(int idTipoDoc) {
        this.idTipoDoc = idTipoDoc;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set getVendedors() {
        return this.vendedors;
    }
    
    public void setVendedors(Set vendedors) {
        this.vendedors = vendedors;
    }




}


