package joyeria;
// Generated 10-may-2010 15:42:23 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Vendedor generated by hbm2java
 */
public class Vendedor  implements java.io.Serializable {


     private int idVendedor;
     private TipoDocumentos tipoDocumentos;
     private String nroDocumento;
     private String nombre;
     private String telefono1;
     private String telefono2;
     private String direccion;
     private String codPostal;
     private String provincia;
     private String departamento;
     private String pais;
     private Date fechaIngreso;
     private Date fechaCese;
     private String email;

    public Vendedor() {
    }

    public Vendedor(int idVendedor, TipoDocumentos tipoDocumentos, String nroDocumento, String nombre, String telefono1, String telefono2, String direccion, String codPostal, String provincia, String departamento, String pais, Date fechaIngreso, Date fechaCese, String email) {
       this.idVendedor = idVendedor;
       this.tipoDocumentos = tipoDocumentos;
       this.nroDocumento = nroDocumento;
       this.nombre = nombre;
       this.telefono1 = telefono1;
       this.telefono2 = telefono2;
       this.direccion = direccion;
       this.codPostal = codPostal;
       this.provincia = provincia;
       this.departamento = departamento;
       this.pais = pais;
       this.fechaIngreso = fechaIngreso;
       this.fechaCese = fechaCese;
       this.email = email;
    }
   
    public int getIdVendedor() {
        return this.idVendedor;
    }
    
    public void setIdVendedor(int idVendedor) {
        this.idVendedor = idVendedor;
    }
    public TipoDocumentos getTipoDocumentos() {
        return this.tipoDocumentos;
    }
    
    public void setTipoDocumentos(TipoDocumentos tipoDocumentos) {
        this.tipoDocumentos = tipoDocumentos;
    }
    public String getNroDocumento() {
        return this.nroDocumento;
    }
    
    public void setNroDocumento(String nroDocumento) {
        this.nroDocumento = nroDocumento;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getTelefono1() {
        return this.telefono1;
    }
    
    public void setTelefono1(String telefono1) {
        this.telefono1 = telefono1;
    }
    public String getTelefono2() {
        return this.telefono2;
    }
    
    public void setTelefono2(String telefono2) {
        this.telefono2 = telefono2;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getCodPostal() {
        return this.codPostal;
    }
    
    public void setCodPostal(String codPostal) {
        this.codPostal = codPostal;
    }
    public String getProvincia() {
        return this.provincia;
    }
    
    public void setProvincia(String provincia) {
        this.provincia = provincia;
    }
    public String getDepartamento() {
        return this.departamento;
    }
    
    public void setDepartamento(String departamento) {
        this.departamento = departamento;
    }
    public String getPais() {
        return this.pais;
    }
    
    public void setPais(String pais) {
        this.pais = pais;
    }
    public Date getFechaIngreso() {
        return this.fechaIngreso;
    }
    
    public void setFechaIngreso(Date fechaIngreso) {
        this.fechaIngreso = fechaIngreso;
    }
    public Date getFechaCese() {
        return this.fechaCese;
    }
    
    public void setFechaCese(Date fechaCese) {
        this.fechaCese = fechaCese;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }




}


