/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * VentanaPadre.java
 *
 * Created on 29-abr-2010, 14:22:11
 */

package gui;
import gui.Familia.*;
import gui.TipoDoc.*;
import gui.Proveedor.*;
import gui.Producto.*;
import gui.Vendedor.*;
import gui.Ingreso.*;
/**
 *
 * @author familia
 */
public class VentanaPadre extends javax.swing.JFrame {

    /** Creates new form VentanaPadre */
    public VentanaPadre() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mpFamilia = new javax.swing.JMenu();
        smAgregar = new javax.swing.JMenuItem();
        smActualizar = new javax.swing.JMenuItem();
        smEliminar = new javax.swing.JMenuItem();
        mpTipDoc = new javax.swing.JMenu();
        smAgregarTD = new javax.swing.JMenuItem();
        smActualizarTD = new javax.swing.JMenuItem();
        smEliminarTD = new javax.swing.JMenuItem();
        mpProveedor = new javax.swing.JMenu();
        smAgregarP = new javax.swing.JMenuItem();
        smActualizarP = new javax.swing.JMenuItem();
        smEliminarP = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de Informacion para la Gestion de una empresa de Joyería");

        escritorio.setBackground(new java.awt.Color(255, 255, 255));

        jMenu1.setText("Matenimiento");
        jMenu1.setFont(new java.awt.Font("Arial", 0, 12));

        mpFamilia.setText("Familia");
        mpFamilia.setFont(new java.awt.Font("Arial", 0, 12));

        smAgregar.setFont(new java.awt.Font("Arial", 0, 12));
        smAgregar.setText("Agregar");
        smAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smAgregarActionPerformed(evt);
            }
        });
        mpFamilia.add(smAgregar);

        smActualizar.setFont(new java.awt.Font("Arial", 0, 12));
        smActualizar.setText("Actualizar");
        smActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smActualizarActionPerformed(evt);
            }
        });
        mpFamilia.add(smActualizar);

        smEliminar.setFont(new java.awt.Font("Arial", 0, 12));
        smEliminar.setText("Eliminar");
        smEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smEliminarActionPerformed(evt);
            }
        });
        mpFamilia.add(smEliminar);

        jMenu1.add(mpFamilia);

        mpTipDoc.setText("Tipo Documento");
        mpTipDoc.setFont(new java.awt.Font("Arial", 0, 12));

        smAgregarTD.setFont(new java.awt.Font("Arial", 0, 12));
        smAgregarTD.setText("Agregar");
        smAgregarTD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smAgregarTDActionPerformed(evt);
            }
        });
        mpTipDoc.add(smAgregarTD);

        smActualizarTD.setFont(new java.awt.Font("Arial", 0, 12));
        smActualizarTD.setText("Actualizar");
        smActualizarTD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smActualizarTDActionPerformed(evt);
            }
        });
        mpTipDoc.add(smActualizarTD);

        smEliminarTD.setFont(new java.awt.Font("Arial", 0, 12));
        smEliminarTD.setText("Eliminar");
        smEliminarTD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smEliminarTDActionPerformed(evt);
            }
        });
        mpTipDoc.add(smEliminarTD);

        jMenu1.add(mpTipDoc);

        mpProveedor.setText("Proveedor");
        mpProveedor.setFont(new java.awt.Font("Arial", 0, 12));

        smAgregarP.setFont(new java.awt.Font("Arial", 0, 12));
        smAgregarP.setText("Agregar");
        smAgregarP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smAgregarPActionPerformed(evt);
            }
        });
        mpProveedor.add(smAgregarP);

        smActualizarP.setFont(new java.awt.Font("Arial", 0, 12));
        smActualizarP.setText("Actualizar");
        smActualizarP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smActualizarPActionPerformed(evt);
            }
        });
        mpProveedor.add(smActualizarP);

        smEliminarP.setFont(new java.awt.Font("Arial", 0, 12));
        smEliminarP.setText("Eliminar");
        smEliminarP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smEliminarPActionPerformed(evt);
            }
        });
        mpProveedor.add(smEliminarP);

        jMenu1.add(mpProveedor);

        jMenu2.setText("Producto");
        jMenu2.setFont(new java.awt.Font("Arial", 0, 12));

        jMenuItem1.setFont(new java.awt.Font("Arial", 0, 12));
        jMenuItem1.setText("Agregar");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuItem2.setFont(new java.awt.Font("Arial", 0, 12));
        jMenuItem2.setText("Actualizar");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuItem3.setFont(new java.awt.Font("Arial", 0, 12));
        jMenuItem3.setText("Eliminar");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenu1.add(jMenu2);

        jMenu3.setText("Vendedor");
        jMenu3.setFont(new java.awt.Font("Arial", 0, 12));

        jMenuItem4.setFont(new java.awt.Font("Arial", 0, 12));
        jMenuItem4.setText("Agregar");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem4);

        jMenuItem5.setFont(new java.awt.Font("Arial", 0, 12));
        jMenuItem5.setText("Actualizar");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem5);

        jMenuItem6.setFont(new java.awt.Font("Arial", 0, 12));
        jMenuItem6.setText("Eliminar");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem6);

        jMenu1.add(jMenu3);

        jMenuBar1.add(jMenu1);

        jMenu4.setText("Movimientos");
        jMenu4.setFont(new java.awt.Font("Arial", 0, 12));

        jMenu5.setText("Ingreso");
        jMenu5.setFont(new java.awt.Font("Arial", 0, 12));

        jMenuItem7.setFont(new java.awt.Font("Arial", 0, 12));
        jMenuItem7.setText("Agregar");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem7);

        jMenu4.add(jMenu5);

        jMenu6.setText("Detalle Ingreso");
        jMenu6.setFont(new java.awt.Font("Arial", 0, 12));

        jMenuItem8.setFont(new java.awt.Font("Arial", 0, 12));
        jMenuItem8.setText("Agregar");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem8);

        jMenu4.add(jMenu6);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio, javax.swing.GroupLayout.DEFAULT_SIZE, 663, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 443, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void smAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smAgregarActionPerformed
        // TODO add your handling code here:
        insFamilia insfam = new insFamilia();
        escritorio.add(insfam);
        insfam.show();
    }//GEN-LAST:event_smAgregarActionPerformed

    private void smActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smActualizarActionPerformed
        // TODO add your handling code here:
        upFamilia updfam = new upFamilia();
        escritorio.add(updfam);
        updfam.show();
    }//GEN-LAST:event_smActualizarActionPerformed

    private void smEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smEliminarActionPerformed
        // TODO add your handling code here:
        delFamilia delfam = new delFamilia();
        escritorio.add(delfam);
        delfam.show();
    }//GEN-LAST:event_smEliminarActionPerformed

    private void smAgregarTDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smAgregarTDActionPerformed
        // TODO add your handling code here:
        insTipoDoc instdoc = new insTipoDoc();
        escritorio.add(instdoc);
        instdoc.show();
    }//GEN-LAST:event_smAgregarTDActionPerformed

    private void smActualizarTDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smActualizarTDActionPerformed
        // TODO add your handling code here:
        updTipoDoc updtdoc = new updTipoDoc();
        escritorio.add(updtdoc);
        updtdoc.show();
    }//GEN-LAST:event_smActualizarTDActionPerformed

    private void smEliminarTDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smEliminarTDActionPerformed
        // TODO add your handling code here:
        delTipoDoc  deltdoc = new delTipoDoc();
        escritorio.add(deltdoc);
        deltdoc.show();
    }//GEN-LAST:event_smEliminarTDActionPerformed

    private void smAgregarPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smAgregarPActionPerformed
        // TODO add your handling code here:
        insProveedor insprov = new insProveedor();
        escritorio.add(insprov);
        insprov.show();
    }//GEN-LAST:event_smAgregarPActionPerformed

    private void smActualizarPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smActualizarPActionPerformed
        // TODO add your handling code here:
        updProveedor updprov = new updProveedor();
        escritorio.add(updprov);
        updprov.show();
    }//GEN-LAST:event_smActualizarPActionPerformed

    private void smEliminarPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smEliminarPActionPerformed
        // TODO add your handling code here:
        delProveedor delprov = new delProveedor();
        escritorio.add(delprov);
        delprov.show();
    }//GEN-LAST:event_smEliminarPActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        insProducto insproc = new insProducto();
        escritorio.add(insproc);
        insproc.show();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        updProducto updprod = new updProducto();
        escritorio.add(updprod);
        updprod.show();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        delProducto delprod = new delProducto();
        escritorio.add(delprod);
        delprod.show();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        insVendedor insvend = new insVendedor();
        escritorio.add(insvend);
        insvend.show();
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        updVendedor updvend = new updVendedor();
        escritorio.add(updvend);
        updvend.show();
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
        delVendedor delvend = new delVendedor();
        escritorio.add(delvend);
        delvend.show();
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        // TODO add your handling code here:
        insIngreso insing = new insIngreso();
        escritorio.add(insing);
        insing.show();
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        // TODO add your handling code here:
        insDellIngreso insd = new insDellIngreso();
        escritorio.add(insd);
        insd.show();
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPadre().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenu mpFamilia;
    private javax.swing.JMenu mpProveedor;
    private javax.swing.JMenu mpTipDoc;
    private javax.swing.JMenuItem smActualizar;
    private javax.swing.JMenuItem smActualizarP;
    private javax.swing.JMenuItem smActualizarTD;
    private javax.swing.JMenuItem smAgregar;
    private javax.swing.JMenuItem smAgregarP;
    private javax.swing.JMenuItem smAgregarTD;
    private javax.swing.JMenuItem smEliminar;
    private javax.swing.JMenuItem smEliminarP;
    private javax.swing.JMenuItem smEliminarTD;
    // End of variables declaration//GEN-END:variables

}
