/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * view.java
 *
 * Created on 16/10/2010, 09:12:43 AM
 */
package subneting;

import javax.swing.JOptionPane;

/**
 *
 * @author net
 */
public class view extends javax.swing.JApplet {

    /** Initializes the applet view */
    public void init() {
        try {
            java.awt.EventQueue.invokeAndWait(new Runnable() {

                public void run() {
                    initComponents();
                }
            });
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    /** This method is called from within the init() method to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        n1 = new javax.swing.JTextField();
        n2 = new javax.swing.JTextField();
        n3 = new javax.swing.JTextField();
        n4 = new javax.swing.JTextField();
        n5 = new javax.swing.JTextField();
        n6 = new javax.swing.JTextField();
        n7 = new javax.swing.JTextField();
        n8 = new javax.swing.JTextField();
        resultado = new javax.swing.JLabel();
        btnEjecutar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtConvertir = new javax.swing.JTextField();
        btnCalcular = new javax.swing.JButton();
        lbl1 = new javax.swing.JLabel();
        lbl2 = new javax.swing.JLabel();
        lbl3 = new javax.swing.JLabel();
        lbl5 = new javax.swing.JLabel();
        lbl6 = new javax.swing.JLabel();
        lbl4 = new javax.swing.JLabel();
        lbl7 = new javax.swing.JLabel();
        lbl8 = new javax.swing.JLabel();
        btnLimpiezaObtener = new javax.swing.JButton();
        btnLimpieza01 = new javax.swing.JButton();

        jLabel1.setText("Ingrese 0 y 1");

        resultado.setText("Resultado");

        btnEjecutar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/accessories-calculator.png"))); // NOI18N
        btnEjecutar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEjecutarActionPerformed(evt);
            }
        });

        jLabel2.setText("Convertir a Binario");

        btnCalcular.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/accessories-calculator.png"))); // NOI18N
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });

        lbl1.setText("x");

        lbl2.setText("x");

        lbl3.setText("x");

        lbl5.setText("x");

        lbl6.setText("x");

        lbl4.setText("x");

        lbl7.setText("x");

        lbl8.setText("x");

        btnLimpiezaObtener.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/edit-clear.png"))); // NOI18N
        btnLimpiezaObtener.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiezaObtenerActionPerformed(evt);
            }
        });

        btnLimpieza01.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/edit-clear.png"))); // NOI18N
        btnLimpieza01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpieza01ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(n1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(n2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(n3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(n4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(n5, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(n6, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(n7, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(n8, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEjecutar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnLimpieza01)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(resultado))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl8))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtConvertir, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCalcular)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnLimpiezaObtener)))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(resultado)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(n1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(n2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(n3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(n4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(n5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(n6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(n7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(n8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEjecutar)))
                    .addComponent(btnLimpieza01))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtConvertir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCalcular))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl1)
                            .addComponent(lbl2)
                            .addComponent(lbl3)
                            .addComponent(lbl4)
                            .addComponent(lbl5)
                            .addComponent(lbl6)
                            .addComponent(lbl7)
                            .addComponent(lbl8)))
                    .addComponent(btnLimpiezaObtener))
                .addContainerGap(16, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnEjecutarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEjecutarActionPerformed
        // TODO add your handling code here:
        try {
            int nn1 = Integer.parseInt(n1.getText());
            int nn2 = Integer.parseInt(n2.getText());
            int nn3 = Integer.parseInt(n3.getText());
            int nn4 = Integer.parseInt(n4.getText());
            int nn5 = Integer.parseInt(n5.getText());
            int nn6 = Integer.parseInt(n6.getText());
            int nn7 = Integer.parseInt(n7.getText());
            int nn8 = Integer.parseInt(n8.getText());

            if (nn1 == 1) {
                nn1 = 128;
            } else {
                nn1 = 0;
            }
            if (nn2 == 1) {
                nn2 = 64;
            } else {
                nn2 = 0;
            }
            if (nn3 == 1) {
                nn3 = 32;
            } else {
                nn3 = 0;
            }
            if (nn4 == 1) {
                nn4 = 16;
            } else {
                nn4 = 0;
            }
            if (nn5 == 1) {
                nn5 = 8;
            } else {
                nn5 = 0;
            }
            if (nn6 == 1) {
                nn6 = 4;
            } else {
                nn6 = 0;
            }
            if (nn7 == 1) {
                nn7 = 2;
            } else {
                nn7 = 0;
            }
            if (nn8 == 1) {
                nn8 = 1;
            } else {
                nn8 = 0;
            }


            int total = nn1 + nn2 + nn3 + nn4 + nn5 + nn6 + nn7 + nn8;

            resultado.setText(String.valueOf(total));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Debe Ingresar datos");
        }

}//GEN-LAST:event_btnEjecutarActionPerformed

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        // TODO add your handling code here:
        try {
            int obtener = Integer.parseInt(txtConvertir.getText());

            if (obtener >= 128) {
                obtener = obtener - 128;
                lbl1.setText("1");
            } else {
                lbl1.setText("0");
            }
            if (obtener >= 64) {
                obtener = obtener - 64;
                lbl2.setText("1");
            } else {
                lbl2.setText("0");
            }
            if (obtener >= 32) {
                obtener = obtener - 32;
                lbl3.setText("1");
            } else {
                lbl3.setText("0");
            }
            if (obtener >= 16) {
                obtener = obtener - 16;
                lbl4.setText("1");
            } else {
                lbl4.setText("0");
            }
            if (obtener >= 8) {
                obtener = obtener - 8;
                lbl5.setText("1");
            } else {
                lbl5.setText("0");
            }
            if (obtener >= 4) {
                obtener = obtener - 4;
                lbl6.setText("1");
            } else {
                lbl6.setText("0");
            }
            if (obtener >= 2) {
                obtener = obtener - 2;
                lbl7.setText("1");
            } else {
                lbl7.setText("0");
            }
            if (obtener >= 1) {
                obtener = obtener - 1;
                lbl8.setText("1");
            } else {
                lbl8.setText("0");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Debe Ingresar datos");
        }


    }//GEN-LAST:event_btnCalcularActionPerformed

    private void btnLimpiezaObtenerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiezaObtenerActionPerformed
        // TODO add your handling code here:
        txtConvertir.setText("");
    }//GEN-LAST:event_btnLimpiezaObtenerActionPerformed

    private void btnLimpieza01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpieza01ActionPerformed
        // TODO add your handling code here:
        n1.setText("");
        n2.setText("");
        n3.setText("");
        n4.setText("");
        n5.setText("");
        n6.setText("");
        n7.setText("");
        n8.setText("");
    }//GEN-LAST:event_btnLimpieza01ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcular;
    private javax.swing.JButton btnEjecutar;
    private javax.swing.JButton btnLimpieza01;
    private javax.swing.JButton btnLimpiezaObtener;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lbl1;
    private javax.swing.JLabel lbl2;
    private javax.swing.JLabel lbl3;
    private javax.swing.JLabel lbl4;
    private javax.swing.JLabel lbl5;
    private javax.swing.JLabel lbl6;
    private javax.swing.JLabel lbl7;
    private javax.swing.JLabel lbl8;
    private javax.swing.JTextField n1;
    private javax.swing.JTextField n2;
    private javax.swing.JTextField n3;
    private javax.swing.JTextField n4;
    private javax.swing.JTextField n5;
    private javax.swing.JTextField n6;
    private javax.swing.JTextField n7;
    private javax.swing.JTextField n8;
    private javax.swing.JLabel resultado;
    private javax.swing.JTextField txtConvertir;
    // End of variables declaration//GEN-END:variables
}
