package productos;
// Generated 12/10/2010 08:40:13 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Producto generated by hbm2java
 */
public class Producto  implements java.io.Serializable {


     private Integer codigo;
     private String descripcion;
     private String categoria;
     private Integer cantidad;
     private Double costo;
     private Double precio;
     private Date fecing;
     private String estado;

    public Producto() {
    }

    public Producto(String descripcion, String categoria, Integer cantidad, Double costo, Double precio, Date fecing, String estado) {
       this.descripcion = descripcion;
       this.categoria = categoria;
       this.cantidad = cantidad;
       this.costo = costo;
       this.precio = precio;
       this.fecing = fecing;
       this.estado = estado;
    }
   
    public Integer getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(Integer codigo) {
        this.codigo = codigo;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getCategoria() {
        return this.categoria;
    }
    
    public void setCategoria(String categoria) {
        this.categoria = categoria;
    }
    public Integer getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(Integer cantidad) {
        this.cantidad = cantidad;
    }
    public Double getCosto() {
        return this.costo;
    }
    
    public void setCosto(Double costo) {
        this.costo = costo;
    }
    public Double getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(Double precio) {
        this.precio = precio;
    }
    public Date getFecing() {
        return this.fecing;
    }
    
    public void setFecing(Date fecing) {
        this.fecing = fecing;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }




}


