/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * BeanOnPanel.java
 *
 * Created on 17/11/2010, 09:15:27 AM
 */

package b;

import java.awt.Panel;

/**
 *
 * @author willly
 */
public class BeanOnPanel extends Panel {

    /** Creates new form BeanOnPanel */
    public BeanOnPanel() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
