package prueba;
// Generated 16/09/2010 11:25:20 PM by Hibernate Tools 3.2.1.GA



/**
 * Usuarios generated by hbm2java
 */
public class Usuarios  implements java.io.Serializable {


     private int codigo;
     private String usuario;
     private String password;

    public Usuarios() {
    }

    public Usuarios(int codigo, String usuario, String password) {
       this.codigo = codigo;
       this.usuario = usuario;
       this.password = password;
    }
   
    public int getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(int codigo) {
        this.codigo = codigo;
    }
    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }




}


